version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/app
    env_file: .env
    container_name: clean-arch-web
    security_opt:
      - seccomp:unconfined
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: clean-arch-db
    ports:
      - 54321:5432
    volumes:
      - clean-arch-db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  clean-arch-db:
